version: "3.8"
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  web:
    image: jbc/object-data
    environment:
      WAIT_HOSTS: mongodb:27017
    command: java -jar /app.jar
    ports:
      - target: 8081
        published: 8081
